# CREDIT: https://github.com/shren207/nextjs-docker-compose
services:
  test:
    build: .
    user: 1000:1000
    ports:
      - 3000:3000
    restart: always
    working_dir: /app
    volumes:
      - $PWD:/app
      - test_node_modules:/app/node_modules

    command: sleep infinity
    # command: ./serve.sh
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.whoami.rule=Host(`portfolio.iamon99.com`)'
    #   - 'traefik.http.routers.whoami.entrypoints=websecure'
    #   - 'traefik.http.routers.whoami.tls.certresolver=myresolver'

volumes:
  test_node_modules:
